"""added field id fot User model

Revision ID: 64153eb3a2b4
Revises: 4e9f060148c9
Create Date: 2026-02-12 12:43:44.052281

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64153eb3a2b4"
down_revision: Union[str, Sequence[str], None] = "4e9f060148c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("assignee_id", sa.UUID(), nullable=False))
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(None, "tasks", "users", ["assignee_id"], ["id"])
    op.drop_column("tasks", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"]
    )
    op.drop_column("tasks", "assignee_id")
    # ### end Alembic commands ###
