"""added slug to Team

Revision ID: e8d3efcadeb2
Revises: 2a90752f83fe
Create Date: 2026-02-07 19:14:43.541133

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8d3efcadeb2"
down_revision: Union[str, Sequence[str], None] = "2a90752f83fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("slug", sa.String(length=20), nullable=False))
    op.create_index(op.f("ix_teams_slug"), "teams", ["slug"], unique=True)
    op.create_unique_constraint(None, "teams", ["title"])
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("USER", "MANAGER", "ADMIN", name="user_role"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("USER", "MANAGER", "ADMIN", name="user_role"),
        nullable=True,
    )
    op.drop_constraint(None, "teams", type_="unique")
    op.drop_index(op.f("ix_teams_slug"), table_name="teams")
    op.drop_column("teams", "slug")
    # ### end Alembic commands ###
