"""added slug to User

Revision ID: 1511cbdcea60
Revises: e8d3efcadeb2
Create Date: 2026-02-07 19:33:23.000515

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1511cbdcea60"
down_revision: Union[str, Sequence[str], None] = "e8d3efcadeb2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("slug", sa.String(length=30), nullable=False))
    op.create_index(op.f("ix_users_slug"), "users", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_slug"), table_name="users")
    op.drop_column("users", "slug")
    # ### end Alembic commands ###
