"""added slug for Task model

Revision ID: 4e9f060148c9
Revises: 1511cbdcea60
Create Date: 2026-02-09 16:25:16.709905

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e9f060148c9"
down_revision: Union[str, Sequence[str], None] = "1511cbdcea60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("slug", sa.String(length=20), nullable=False))
    op.add_column("tasks", sa.Column("team_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_tasks_slug"), "tasks", ["slug"], unique=True)
    op.create_foreign_key(None, "tasks", "teams", ["team_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_slug"), table_name="tasks")
    op.drop_column("tasks", "team_id")
    op.drop_column("tasks", "slug")
    # ### end Alembic commands ###
