"""added text to Comment Model

Revision ID: 755b5a5fe203
Revises: 7f7c60938c63
Create Date: 2026-02-13 15:50:19.576585

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "755b5a5fe203"
down_revision: Union[str, Sequence[str], None] = "7f7c60938c63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("text", sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "text")
    # ### end Alembic commands ###
