from typing import Protocol, Optional, Sequence
from .entities import Task


class TaskRepository(Protocol):
    async def get_by_slug_for_team(self, slug: str, team_id: int) -> Optional[Task]: ...
    async def get_all(self) -> Sequence[Task]: ...
    async def add(self, task: Task) -> Task: ...
    async def update(self, task: Task) -> Task: ...
    async def delete(self, task: Task) -> None: ...
